add arguments that allow different optim for G and D; add SGD for optim
rkansal47/MPGAN pull request #22
Opened 2023-05-10 03:17 UTC by AnniLi1212

2023-11-07 22:18 UTC, rkansal47 requested changes

2023-11-07 22:18 UTC, rkansal47 commented on setup_training.py
> +        "--use_different_optimizers",
`--use_different_optimizers` -> `--use-different-optimizers`

2023-11-07 22:18 UTC, rkansal47 commented on train.py
> +    logging.info("Args initalized in: %s seconds" % (args_end_time - args_start_time))
Could you reduce the timing statements now? I think some of these will take negligible time (e.g. this one).

2023-11-07 22:19 UTC, rkansal47 commented
Looks good! Asked for some minor changes, and reducing the timing statements now.

2023-11-08 05:28 UTC, AnniLi1212 commented
update profilling, different optim for G and D arg

2024-02-13 21:53 UTC, closed without merging